#!/usr/bin/env python3
import sys, os, time
import argparse

mch_us = "root"
mch_ps = "root"

def crate_ip( crate ):
    return "10.73.{}.128".format(crate+32)

def card_slot( slotnum ):
    return "0x%x" % (0x70+0x2*slotnum)

def reboot( mch_ip, slot_xp ):
    icmd = "ipmitool -v -I lan -H %s -U %s -P %s -T 0x82 -B0 -b7" % (mch_ip, mch_us, mch_ps)
    icmd = icmd + " -t %s raw 0x2E 0x03 0x00 0x00 0x60"

    icard = icmd % slot_xp

    # select dune firmware
    # cmd1 = icard + " 0x40 0x40"

    # reconfigure
    cmd2 = icard + " 0x8 0x8"

    # disable flash access
    #cmd3 = icard + " 0x1 0x1"

    # reboot
    cmd4 = icard + " 0x8 0x0"

    # introduce delay between commands
    cdelay = 1
    
    #print( cmd1 )
    #os.system( cmd1 )
    #time.sleep(cdelay)
    print( cmd2 )
    os.system( cmd2 )
    time.sleep(cdelay)
    #print( cmd3 )
    #os.system( cmd3 )
    #time.sleep(cdelay)
    print( cmd4 )
    os.system( cmd4 )

    return




if __name__=='__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument( '-s', '--slot',
                         help='select specific slot(s)',
                         nargs='+',
                         required = False, type=int )
    parser.add_argument( '-c', '--crate',
                         help='select crate number counting from 0',
                         default = 0, type = int )
    parser.add_argument( '-a', '--address',
                         help='non-standard mch ip',
                         required = False, type = str )
    
    slots  = [*range(1,13)] # all slots
    args   = parser.parse_args()
    crate  = args.crate
    mch_ip = crate_ip( crate )
    if( args.address is not None ):
        mch_ip = args.address
    if( args.slot is not None):
        print(args.slot)
        slots = args.slot

    print( "boot cards in slots {} in crate at {}".format( slots, mch_ip ))

    for s in slots: 
        reboot(mch_ip, card_slot( s ))
    
    # done
    
    
